export const WORKFLOW_STAGES = [
  { id: 'nlmParsePDF', name: 'NLM PDF Parsing' },
  { id: 'doclingParsePDF', name: 'Docling PDF Parsing' },
  { id: 'nlmExtractTables', name: 'Table Extraction' },
  { id: 'indexMarkdown', name: 'Markdown' },
  { id: 'precheck', name: 'Pre-check' },
  { id: 'guessWikidata', name: 'Wikidata' },
  { id: 'extractEmissions', name: 'Emissions Data' },
  { id: 'followUp', name: 'Follow-up' },  
  { id: 'checkDB', name: 'DB Check' },
  { id: 'diffIndustry', name: 'Industry' },
  { id: 'diffGoals', name: 'Climate Goals' },
  { id: 'diffInitiatives', name: 'Initiatives' },
  { id: 'diffBaseYear', name: 'Base Year' },
  { id: 'diffReportingPeriods', name: 'Financial Years' },
  { id: 'saveToAPI', name: 'API Storage' },
  { id: 'wikipediaUpload', name: 'Wikipedia' },
  { id: 'diffTags', name: 'Tags' },
  { id: 'sendCompanyLink', name: 'Review' },
];