export const WORKFLOW_STAGES = [
  { id: 'nlmParsePDF', name: 'NLM PDF Parsing' },
  { id: 'doclingParsePDF', name: 'Docling PDF Parsing' },
  { id: 'nlmExtractTables', name: 'Table Extraction' },
  { id: 'indexMarkdown', name: 'Markdown' },
  { id: 'precheck', name: 'Pre-check' },
  { id: 'guessWikidata', name: 'Wikidata' },
  { id: 'extractEmissions', name: 'Emissions Data' },
  { id: 'followUpScope12', name: 'Follow-up Scope 1+2' },
  { id: 'followUpScope3', name: 'Follow-up Scope 3' },
  { id: 'followUpBiogenic', name: 'Follow-up Biogenic' },
  { id: 'followUpEconomy', name: 'Follow-up Economy' },  
  { id: 'followUpGoals', name: 'Follow-up Goals' },
  { id: 'followUpInitiatives', name: 'Follow-up Initiatives' },
  { id: 'followUpFiscalYear', name: 'Follow-up Fiscal Year' },
  { id: 'followUpCompanyTags', name: 'Follow-up Company Tags' },
  { id: 'followUpBaseYear', name: 'Follow-up Base Year' },
  { id: 'followUpIndustryGics', name: 'Follow-up Industry GICS' },
  { id: 'checkDB', name: 'DB Check' },
  { id: 'diffIndustry', name: 'Industry' },
  { id: 'diffGoals', name: 'Climate Goals' },
  { id: 'diffInitiatives', name: 'Initiatives' },
  { id: 'diffBaseYear', name: 'Base Year' },
  { id: 'diffReportingPeriods', name: 'Reporting Periods' },
  { id: 'saveToAPI', name: 'API Storage' },
  { id: 'wikipediaUpload', name: 'Wikipedia' },
  { id: 'diffTags', name: 'Tags' },
  { id: 'sendCompanyLink', name: 'Review' },
];
