apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-frontend
  namespace: default
  labels:
    app: validate-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validate-frontend
  template:
    metadata:
      labels:
        app: validate-frontend
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: db-migration
          image: ghcr.io/klimatbyran/validate-frontend
          command: ['npm', 'run', 'migrate']
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/validate-frontend
      containers:
        - image: ghcr.io/klimatbyran/validate-frontend
          name: validate-frontend
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: DATABASE_URL
            - name: API_BASE_URL
              value: http://validate-frontend/api
imagePullPolicy: Always